
const ROLE = {
 ADMIN: "ADMIN",
 CLIENT: "CLIENT",
 CUSTOMUER: "CUSTOMUER"
}
const STATUS_CODES = {
 OK: 200,
 INTERNAL_SERVER_ERROR: 500,
 BAD_REQUEST: 400,
 NOT_FOUND: 404,
 CREATED: 201,
 UNAUTHORISED: 401
}
module.exports = {
 ROLE,STATUS:STATUS_CODES
}
